name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - uses: actions/cache@v2.1.6
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm install --production

    - name: Push to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      run: |
        # Hard-code user configuration
        git config user.email "celfring@gmail.com"
        git config user.name "Caitlin Elfring"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

        # https://github.com/peers/peerjs#faq
        # avoid treating warnings as errors
        CI=false npm run deploy
